### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by darribas** [rsbivand/ectqg19-workshop#4]
@rsbivand , here's a plan for the data to use. Since we'll be demonstrating similar functionality in R/Python it might be good to use the same data. Over today and tomorrow, I'm planning on compiling a small dataset with the following:

- Luxembourg regions (vector polygons)
- Population estimates from GHSL
- Light intensity from VIIRS
- Some Census or other continuous variable

I think that could be used for pretty much all day, but if you have any additional ideas, we could use them too (maybe this for the morning, something else for the afternoon?). Happy to discuss, but I thought I'd throw this in here to coordinate the conversation.

**Comment by rsbivand** [comment]
Sounds good; GHSL is https://ghsl.jrc.ec.europa.eu/ and VIIRS is https://earthdata.nasa.gov/earth-observation-data/near-real-time/download-nrt-data/viirs-nrt ? I found https://data.public.lu/en/datasets/remarkable-trees/  with shapefile 
[anf_remarkable_trees_shapefiles.zip](https://github.com/rsbivand/ectqg19-workshop/files/3549702/anf_remarkable_trees_shapefiles.zip), with others maybe from the same portal.

**Comment by darribas** [comment]
Cool, I'll try to push changes later today!

**Comment by darribas** [comment]
OK, new setup live as of 01b143f5aef6a1941ea9509979f5e65321e3d0c9. I'm closing this but feel free to reopen if needed (I'll be pushing a couple more changes now on materials using these data).
